name: Deploy to Production
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via Git Clone
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Останавливаем PM2 процесс перед обновлением
            if command -v pm2 &> /dev/null; then
              echo "Stopping PM2 process..."
              pm2 stop dlc || echo "PM2 process 'dlc' not running"
              pm2 delete dlc || echo "PM2 process 'dlc' not found"
            fi

            # Полностью очищаем папку и создаем заново
            sudo rm -rf /var/www/dlc
            sudo mkdir -p /var/www/dlc
            sudo chown -R ubuntu:ubuntu /var/www/dlc

            # Переходим в папку и клонируем репозиторий
            cd /var/www/dlc
            git clone -b main https://github.com/Robocotik/hakathon_iu5_2025_frontend.git .

            # Создание env файла
            echo "Creating .env file..."
            touch .env
            echo NEXT_PUBLIC_API_URL=http://109.120.190.243:8001/api >> .env

            # Устанавливаем зависимости
            echo "Installing dependencies..."
            npm ci

            # Собираем проект
            echo "Building project..."
            npm run build

            # Устанавливаем PM2 если его нет
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Устанавливаем production зависимости
            echo "Installing production dependencies..."
            npm ci --production

            # Запускаем приложение
            echo "Starting application..."
            pm2 start npm --name "dlc" -- start
            pm2 save
            pm2 list

  notify_success:
    name: Success Message
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram Success Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Изменения успешно задеплоены

            🔗 Ссылка на прод 🔗
            ${{ secrets.SERVER_HOST || 'Отсутствует' }}

  notify_failure:
    name: Failure Message
    if: ${{ needs.deploy.result == 'failure' }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Failure Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❗️ Произошла ошибка во время деплоя

            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
