name: Test DLC Frontend CI
on: [push, workflow_dispatch, pull_request]
jobs:
  install-cache:
    name: Install cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v5

      - name: Cache npm dependencies
        id: cache-ci
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        if: steps.cache-ci.outputs.cache-hit != 'true'
        run: npm ci
  eslint-check:
    name: Eslint check
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        id: cache-ci
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Run eslint check
        run: npm run eslint:fix

  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        id: cache-ci
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Run prettier fix
        run: npm run prettier:fix

  typescript-check:
    name: TypeScript check
    needs: install-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        id: cache-ci
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Run TypeScript check
        run: npm run ts:check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - install-cache
      - eslint-check
      - prettier-check
      - typescript-check
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v5

      - name: Restore npm cache
        uses: actions/cache@v4
        id: cache-ci
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Создание env файла
        run: |
          touch .env
          echo NEXT_PUBLIC_API_URL=http://109.120.190.243:8001/api >> .env
          cat .env

      - name: Build project
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next
            package.json
            package-lock.json
          retention-days: 1
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./

      - name: Clean server directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R ubuntu:ubuntu /var/www/dlc
            sudo rm -rf /var/www/dlc/*

      - name: Deploy to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: '.next,package.json,package-lock.json'
          target: '/var/www/dlc'
          overwrite: true

      - name: Install dependencies and start on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Устанавливаем PM2 если его нет
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Переходим в папку проекта
            cd /var/www/dlc

            # Устанавливаем зависимости
            npm ci --production

            # Перезапускаем приложение
            pm2 restart dlc || pm2 start npm --name "dlc" -- start
            pm2 save
  notify_success:
    name: Success Message
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram Success Message
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            ✅ Изменения успешно задеплоены

            🔗 Ссылка на прод 🔗
            ${{ secrets.SERVER_HOST || 'Отсутствует' }}

  notify_failure:
    name: Failure Message
    if: ${{ needs.deploy.result == 'failure' }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Failure Message
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            ❗️ Произошла ошибка во время деплоя

            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
